version: 2
updates:
  - package-ecosystem: cargo
    directory: "/ssh-hunt"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
